CREATE TABLE IF NOT EXISTS suppliers(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  contact TEXT NOT NULL
);
DROP TABLE suppliers;
CREATE TABLE IF NOT EXISTS orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  supplierId INTEGER NOT NULL,
  productId INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  total REAL NOT NULL,
  timestamp TEXT NOT NULL,
  FOREIGN KEY (supplierId) REFERENCES suppliers(id)
);
CREATE TABLE IF NOT EXISTS product(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  amount TEXT NOT NULL
);*/
